# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rfinance}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toni Karhu"]
  s.date = %q{2010-08-12}
  s.default_executable = %q{rfinance.rb}
  s.description = %q{The purpose of rfinace is to provide financial information for data mining from the internet. I trade stocks, options and futures as a hobby. 
    Often some of the strategies that i have used include looking at earnings dates for stocks and investing in these dates with complex options strategies. To find
    these opportunities i need some information. I need information about earnings dates, i need information about options chains, i need information about volatility skews.
    Also as a long term investor i want to invest in companies that are rated highly by online services like msn money ,
    fool, yahoo etc.}
  s.email = %q{tonikarhu@gmail.com}
  s.executables = ["rfinance.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data/chains/GOOG-2010-12.txt",
     "data/earnings/earnings.txt",
     "data/spx.txt",
     "features/downloadChainsForTicker.feature",
     "features/downloadStockscouterData.feature",
     "features/downloadearnings.feature",
     "features/rfinance.feature",
     "features/step_definitions/downloadChainsForTicker_steps.rb",
     "features/step_definitions/downloadearnings_steps.rb",
     "features/step_definitions/rfinance_steps.rb",
     "features/support/env.rb",
     "finance.mm",
     "lib/LoadSPX.rb",
     "lib/downloadUtilities.rb",
     "lib/earningsscraper.rb",
     "lib/economicscraper.rb",
     "lib/ivolatility.rb",
     "lib/jobrunner.rb",
     "lib/loadStatistics.rb",
     "lib/loadstockscouter.rb",
     "lib/loadtodayschains500.rb",
     "lib/model/chain.rb",
     "lib/model/earning.rb",
     "lib/model/earnings.rb",
     "lib/model/ticker.rb",
     "lib/optionschainsscraper.rb",
     "lib/rfinance.rb",
     "lib/util.rb",
     "log/error.log",
     "rfinance.gemspec",
     "test/helper.rb",
     "test/test_rfinance.rb"
  ]
  s.homepage = %q{http://github.com/tonik/rfinance}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A ruby gem for downloading financial data}
  s.test_files = [
    "test/helper.rb",
     "test/test_rfinance.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

